### ISSUE TITLE
Failed to setup socket 1.9.4

### ISSUE THREAD

**Issue by cauliflower69** [WillowChat/Thump#39]
http://pastebin.com/ZitAUgwv

**Comment by lopcode** [comment]
I need more than that to help. Please include your `servers.cfg` file (make sure to take out any passwords so I don't see them, too).

Errors like that can happen when you're connecting to the wrong server, or port, or using TLS when the IRC server doesn't support it. The logging needs improvement and I'll put an issue in for it.

**Comment by lopcode** [comment]
Logging improvements issue: https://github.com/CarrotCodes/Thump/issues/40

**Comment by lopcode** [comment]
Closing as logging improvements are in and I'm pretty sure this is a configuration problem.
