### ISSUE TITLE
Support for bouncers or servers that require a password to connect

### ISSUE THREAD

**Issue by GuntherDW** [WillowChat/Thump#48]
There is an option for keys for channels, but an option for passworded servers (or a perform-like option) would be nice.
This would allow people to connect to a bouncer like ZNC, or an entire server that requires a password to connect.

I haven't tested how it would react if it was forced to join channels though. I'll do that after I create the issue.

**Comment by lopcode** [comment]
Nobody's ever asked for it before, so I haven't added it yet. I'll take a look over the next few days and see how much work is involved.

**Comment by GuntherDW** [comment]
As suspected if you force the bot join a channel, it'll just output the messages to any channel, even if it's not in the Channels config setting.

This means that maybe having a bouncer setup for more than just the bot might not be a smart solution if you connect to more than 1 channel.

**Comment by lopcode** [comment]
I decided to tie this in to a registration overhaul, instead of hacking it in, but I'm still actively working on it.

**Comment by lopcode** [comment]
Ended up being ~1000 lines of change in Warren, but the IRC framework support is there now, so I'll look at exposing it with a config option in Thump.

**Comment by lopcode** [comment]
Here's a build for you to try with PASS support (run the mod and "ServerPassword" should show up in your connection configuration, set it to something). https://hopper.bunnies.io/job/CarrotCodes/job/Thump/job/feature%252F1.10/4/artifact/build/libs/Thump-1.10.2-4.2.0.4.jar

**Comment by lopcode** [comment]
@GuntherDW Any chance you could try it out?

**Comment by GuntherDW** [comment]
Should do, will try to report back in a couple hours when I've tried it out.

**Comment by lopcode** [comment]
Ok, this is the latest 1.10.2 build but either should work: https://hopper.bunnies.io/job/CarrotCodes/job/Thump/job/feature%252F1.10/lastSuccessfulBuild/artifact/build/libs/Thump-1.10.2-4.2.0.8.jar

**Comment by GuntherDW** [comment]
It works for connecting to a passworded server (I tried the linked 4.2.0.8 jar in a test instance).
However it does not seem to like my ZNC very much.

In the single player instance the channels, even though I can see the bot forcing me to join the channels, stay red when I type /thump status. Neither do messages that I type come through.
It does state that "IRC state" is "CONNECTED" and the network as "RUNNING".

That was with forge 12.18.3.2185

**Comment by lopcode** [comment]
It could be broken for ZNC servers in some way - I'll close this issue and add another to Warren (the IRC library) for ZNC support. Thanks!

**Comment by GuntherDW** [comment]
ZNC is a bouncer. It kind of acts like a server to the client, but it's merely a bouncer. If configured to it forces you to join the channels and sends a configured amount of lines as a scrollback.

That might be why?

**Comment by lopcode** [comment]
ZNC still emulates an IRC server, and it probably does something I haven't accounted for during registration / connection. I'll take a look when I get time.

**Comment by lopcode** [comment]
Issue tracked here: https://github.com/CarrotCodes/Warren/issues/17
