### ISSUE TITLE
Renaming Example File

### ISSUE THREAD

**Issue by drbyrge** [WillowChat/Thump#50]
I don't see an example file in the config folder. Where can I find this?

**Comment by lopcode** [comment]
What version are you running? There was a bug preventing example config files from being generated, but it was fixed in recent versions.

**Comment by drbyrge** [comment]
It was the last release version for 1.7.0. It says it is trying to connect
to example and I have set the server address, etc in the server.cfg.

**Comment by lopcode** [comment]
For that version of Minecraft, the config file is in `config/thump/server.cfg` I believe. Newer versions are in `config/thump/services/irc.cfg`.
