### ISSUE TITLE
Mark latest version as 1.11.2

### ISSUE THREAD

**Issue by xbony2** [WillowChat/Thump#51]
(98% sure it should work)

**Comment by xbony2** [comment]
@CarrotEngineer ping? :o it should take only about a few seconds to do this on CurseForge, if you don't mind <3

**Comment by lopcode** [comment]
Sure, I missed this first time and I'm on holiday at the moment, but I'll take a look.

**Comment by CarrotEngineer** [comment]
Sure, I missed this first time and I'm on holiday at the moment, but I'll take a look.

**Comment by lopcode** [comment]
@xbony2 Done, it'll appear here when Curse approve it: https://minecraft.curseforge.com/projects/thump/files/2368713

**Comment by xbony2** [comment]
Thanks :D
